import { useState } from 'react'
import { motion } from 'framer-motion'

const DS_NAMES = {
  avl: 'AVL Tree',
  redblack: 'Red-Black Tree',
  splay: 'Splay Tree',
  skiplist: 'Skip List',
}

// C++ boilerplate templates for each data structure
const CODE_TEMPLATES = {
  avl: `// AVL Tree — Optimal for lookup-heavy workloads
// Generated by Neuro-DS

#include <iostream>
#include <algorithm>

template <typename K>
class AVLTree {
    struct Node {
        K key;
        Node *left, *right;
        int height;
        Node(K k) : key(k), left(nullptr), right(nullptr), height(1) {}
    };
    Node* root = nullptr;

    int height(Node* n) { return n ? n->height : 0; }
    int balance(Node* n) { return n ? height(n->left) - height(n->right) : 0; }

    void updateHeight(Node* n) {
        if (n) n->height = 1 + std::max(height(n->left), height(n->right));
    }

    Node* rotateRight(Node* y) {
        Node* x = y->left; Node* T = x->right;
        x->right = y; y->left = T;
        updateHeight(y); updateHeight(x);
        return x;
    }

    Node* rotateLeft(Node* x) {
        Node* y = x->right; Node* T = y->left;
        y->left = x; x->right = T;
        updateHeight(x); updateHeight(y);
        return y;
    }

    Node* insert(Node* n, K key) {
        if (!n) return new Node(key);
        if (key < n->key) n->left = insert(n->left, key);
        else if (key > n->key) n->right = insert(n->right, key);
        else return n;
        updateHeight(n);
        int bf = balance(n);
        if (bf > 1 && key < n->left->key) return rotateRight(n);
        if (bf < -1 && key > n->right->key) return rotateLeft(n);
        if (bf > 1 && key > n->left->key) { n->left = rotateLeft(n->left); return rotateRight(n); }
        if (bf < -1 && key < n->right->key) { n->right = rotateRight(n->right); return rotateLeft(n); }
        return n;
    }

    bool search(Node* n, K key) {
        if (!n) return false;
        if (key < n->key) return search(n->left, key);
        if (key > n->key) return search(n->right, key);
        return true;
    }

public:
    void insert(K key) { root = insert(root, key); }
    bool search(K key) { return search(root, key); }
};

int main() {
    AVLTree<int> tree;
    // TODO: Add your workload here
    tree.insert(42);
    std::cout << "Found: " << tree.search(42) << std::endl;
    return 0;
}`,

  redblack: `// Red-Black Tree — Optimal for mixed read/write workloads
// Generated by Neuro-DS

#include <iostream>

enum Color { RED, BLACK };

template <typename K>
class RedBlackTree {
    struct Node {
        K key; Color color;
        Node *left, *right, *parent;
        Node(K k, Color c, Node* p) : key(k), color(c), left(nullptr), right(nullptr), parent(p) {}
    };
    Node* root = nullptr;

    void rotateLeft(Node* x) { /* ... standard rotation ... */ }
    void rotateRight(Node* x) { /* ... standard rotation ... */ }
    void insertFixup(Node* z) { /* ... RB fixup logic ... */ }

public:
    void insert(K key) {
        Node* p = nullptr; Node* c = root;
        while (c) { p = c; c = (key < c->key) ? c->left : c->right; }
        Node* z = new Node(key, RED, p);
        if (!p) root = z;
        else if (key < p->key) p->left = z;
        else p->right = z;
        insertFixup(z);
    }

    bool search(K key) {
        Node* c = root;
        while (c) {
            if (key < c->key) c = c->left;
            else if (key > c->key) c = c->right;
            else return true;
        }
        return false;
    }
};

int main() {
    RedBlackTree<int> tree;
    tree.insert(42);
    std::cout << "Found: " << tree.search(42) << std::endl;
    return 0;
}`,

  splay: `// Splay Tree — Optimal for temporal locality workloads
// Generated by Neuro-DS

#include <iostream>

template <typename K>
class SplayTree {
    struct Node {
        K key;
        Node *left, *right, *parent;
        Node(K k, Node* p = nullptr) : key(k), left(nullptr), right(nullptr), parent(p) {}
    };
    Node* root = nullptr;

    void rotateLeft(Node* x) { /* ... rotation ... */ }
    void rotateRight(Node* x) { /* ... rotation ... */ }

    void splay(Node* x) {
        while (x->parent) {
            if (!x->parent->parent) {
                (x == x->parent->left) ? rotateRight(x->parent) : rotateLeft(x->parent);
            } else if (x == x->parent->left && x->parent == x->parent->parent->left) {
                rotateRight(x->parent->parent); rotateRight(x->parent);
            } else if (x == x->parent->right && x->parent == x->parent->parent->right) {
                rotateLeft(x->parent->parent); rotateLeft(x->parent);
            } else if (x == x->parent->right) {
                rotateLeft(x->parent); rotateRight(x->parent);
            } else {
                rotateRight(x->parent); rotateLeft(x->parent);
            }
        }
    }

public:
    void insert(K key) { /* ... insert + splay ... */ }
    bool search(K key) { /* ... search + splay ... */ }
};

int main() {
    SplayTree<int> tree;
    tree.insert(42);
    std::cout << "Found: " << tree.search(42) << std::endl;
    return 0;
}`,

  skiplist: `// Skip List — Optimal for concurrent/range-query workloads
// Generated by Neuro-DS

#include <iostream>
#include <cstdlib>
#include <cstring>

template <typename K>
class SkipList {
    static constexpr int MAX_LEVEL = 16;
    struct Node {
        K key; int level;
        Node** forward;
        Node(K k, int lvl) : key(k), level(lvl) {
            forward = new Node*[lvl + 1]();
        }
        ~Node() { delete[] forward; }
    };

    Node* header; int level = 0;

    int randomLevel() {
        int lvl = 0;
        while (lvl < MAX_LEVEL && rand() % 2 == 0) lvl++;
        return lvl;
    }

public:
    SkipList() { header = new Node(K{}, MAX_LEVEL); }

    void insert(K key) {
        Node* update[MAX_LEVEL + 1] = {};
        Node* curr = header;
        for (int i = level; i >= 0; i--) {
            while (curr->forward[i] && curr->forward[i]->key < key)
                curr = curr->forward[i];
            update[i] = curr;
        }
        int newLevel = randomLevel();
        if (newLevel > level) {
            for (int i = level + 1; i <= newLevel; i++) update[i] = header;
            level = newLevel;
        }
        Node* n = new Node(key, newLevel);
        for (int i = 0; i <= newLevel; i++) {
            n->forward[i] = update[i]->forward[i];
            update[i]->forward[i] = n;
        }
    }

    bool search(K key) {
        Node* curr = header;
        for (int i = level; i >= 0; i--)
            while (curr->forward[i] && curr->forward[i]->key < key)
                curr = curr->forward[i];
        curr = curr->forward[0];
        return curr && curr->key == key;
    }
};

int main() {
    SkipList<int> list;
    list.insert(42);
    std::cout << "Found: " << list.search(42) << std::endl;
    return 0;
}`,
}

export default function CodeExport({ winner }) {
  const [copied, setCopied] = useState(false)
  const code = CODE_TEMPLATES[winner] || '// No template available'
  const dsName = DS_NAMES[winner] || winner

  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${winner}_tree.cpp`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="glass-card p-6 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xl">📝</span>
          <h3 className="text-lg font-semibold text-white">Export C++ Boilerplate</h3>
        </div>
        <div className="flex gap-2">
          <motion.button
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            className="btn-secondary text-sm px-4 py-2"
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </motion.button>
          <motion.button
            whileTap={{ scale: 0.95 }}
            onClick={handleDownload}
            className="btn-primary text-sm px-4 py-2"
          >
            ⬇ Download .cpp
          </motion.button>
        </div>
      </div>

      <p className="text-sm text-gray-400">
        Ready-to-use {dsName} implementation tailored for your workload profile.
      </p>

      {/* Code preview */}
      <div className="relative rounded-xl overflow-hidden">
        <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/10">
          <span className="text-xs text-gray-400 font-mono">{winner}_tree.cpp</span>
          <span className="text-xs text-gray-500">C++17</span>
        </div>
        <pre className="p-4 bg-black/30 text-sm text-gray-300 overflow-x-auto max-h-96 font-mono leading-relaxed">
          <code>{code}</code>
        </pre>
      </div>
    </div>
  )
}
